name: Generate 3D contribution graph
on:
  schedule: [{ cron: "0 18 * * *" }]
  workflow_dispatch:
  push: { branches: [main] }
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: sirdath
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update 3d contribution graph"
          branch: main
